export const techIconData = {
  LegoMan: {
    path: "/models/LegoMan.glb",
    cuboidColliderArgs: [0.7, 1.2, 0.7],
    modelName: "LegoMan",
    scale: [1, 1, 1],
  },
  IconReact: {
    path: "/models/IconReact.glb",
    cuboidColliderArgs: [1.7, 0.25, 1.6],
    modelName: "IconReact",
    scale: [1.5, 1.5, 1.5],
  },
  IconD3: {
    path: "/models/IconD3.glb",
    cuboidColliderArgs: [1.35, 0.25, 1.3],
    modelName: "IconD3",
    scale: [1.2, 1.2, 1.2],
  },

  IconNetscape: {
    path: "/models/IconNetscape.glb",
    cuboidColliderArgs: [1.35, 0.25, 1.3],
    modelName: "IconNetscape",
    scale: [1.2, 1.2, 1.2],
  },
  IconIE: {
    path: "/models/IconIE.glb",
    cuboidColliderArgs: [1.35, 0.25, 1.3],
    modelName: "IconIE",
    scale: [1.2, 1.2, 1.2],
  },
  IconChrome: {
    path: "/models/IconChrome.glb",
    cuboidColliderArgs: [1.35, 0.25, 1.3],
    modelName: "IconChrome",
    scale: [1.2, 1.2, 1.2],
  },
  IconSafari: {
    path: "/models/IconSafari.glb",
    cuboidColliderArgs: [1.35, 0.25, 1.3],
    modelName: "IconSafari",
    scale: [1.2, 1.2, 1.2],
  },
  IconFirefox: {
    path: "/models/IconFirefox.glb",
    cuboidColliderArgs: [1.35, 0.25, 1.3],
    modelName: "IconFirefox",
    scale: [1.9, 1.9, 1.9],
  },
  IconEdge: {
    path: "/models/IconEdge.glb",
    cuboidColliderArgs: [1.35, 0.25, 1.3],
    modelName: "IconEdge",
    scale: [1.2, 1.2, 1.2],
  },
  IconTag: {
    path: "/models/IconTag.glb",
    cuboidColliderArgs: [1.35, 0.25, 1.3],
    modelName: "IconTag",
    scale: [1.2, 1.2, 1.2],
  },
  IconArray: {
    path: "/models/IconArray.glb",
    cuboidColliderArgs: [1.35, 0.25, 1.3],
    modelName: "IconArray",
    scale: [1.2, 1.2, 1.2],
  },
  IconParens: {
    path: "/models/IconParens.glb",
    cuboidColliderArgs: [1.35, 0.25, 1.3],
    modelName: "IconParens",
    scale: [1.2, 1.2, 1.2],
  },
  IconBracket: {
    path: "/models/IconBracket.glb",
    cuboidColliderArgs: [1.35, 0.25, 1.3],
    modelName: "IconBracket",
    scale: [1.2, 1.2, 1.2],
  },
  IconSuzanne: {
    path: "/models/IconSuzanne.glb",
    cuboidColliderArgs: [1.35, 0.25, 1.3],
    modelName: "IconSuzanne",
    scale: [1, 1, 1],
  },
  IconGear: {
    path: "/models/IconGear.glb",
    cuboidColliderArgs: [1.35, 0.25, 1.3],
    modelName: "IconGear",
    scale: [1, 1, 1],
  },
  IconTorus: {
    path: "/models/IconTorus.glb",
    cuboidColliderArgs: [1.35, 0.25, 1.3],
    modelName: "IconTorus",
    scale: [1, 1, 1],
  },
  IconCone: {
    path: "/models/IconCone.glb",
    cuboidColliderArgs: [1.35, 0.25, 1.3],
    modelName: "IconCone",
    scale: [1, 1, 1],
  },
  IconSphere: {
    path: "/models/IconSphere.glb",
    cuboidColliderArgs: [1.35, 0.25, 1.3],
    modelName: "IconSphere",
    scale: [1, 1, 1],
  },
  IconCube: {
    path: "/models/IconCube.glb",
    cuboidColliderArgs: [1.35, 0.25, 1.3],
    modelName: "IconCube",
    scale: [1, 1, 1],
  },
  IconJS: {
    path: "/models/IconJS.glb",
    cuboidColliderArgs: [1.35, 0.25, 1.3],
    modelName: "IconJS",
    scale: [1.2, 1.2, 1.2],
  },
  IconHTML: {
    path: "/models/IconHTML.glb",
    cuboidColliderArgs: [1.35, 0.25, 1.3],
    modelName: "IconHTML",
    scale: [1.2, 1.2, 1.2],
  },
  IconCSS: {
    path: "/models/IconCSS.glb",
    cuboidColliderArgs: [1.35, 0.25, 1.3],
    modelName: "IconCSS",
    scale: [1.2, 1.2, 1.2],
  },

  IconGithub: {
    path: "/models/IconGithub.glb",
    cuboidColliderArgs: [1.35, 0.25, 1.3],
    modelName: "IconGithub",
    scale: [1.2, 1.2, 1.2],
  },
  IconStyledComponents: {
    path: "/models/IconStyledComponents.glb",
    cuboidColliderArgs: [1.35, 0.25, 1.3],
    modelName: "IconStyledComponents",
    scale: [1.2, 1.2, 1.2],
  },
  IconGraphQL: {
    path: "/models/IconGraphQL.glb",
    cuboidColliderArgs: [1.4, 0.25, 1.4],
    modelName: "IconGraphQL",
    scale: [1.5, 1.5, 1.5],
  },
  IconGatsby: {
    path: "/models/IconGatsby.glb",
    cuboidColliderArgs: [1.35, 0.25, 1.3],
    modelName: "IconGatsby",
    scale: [1.2, 1.2, 1.2],
  },
  IconReduxToolkit: {
    path: "/models/IconReduxToolkit.glb",
    cuboidColliderArgs: [1.35, 0.25, 1.3],
    modelName: "IconReduxToolkit",
    scale: [1.2, 1.2, 1.2],
  },
  IconFramerMotion: {
    path: "/models/IconFramerMotion.glb",
    cuboidColliderArgs: [1, 0.25, 1.6],
    modelName: "IconFramerMotion",
    scale: [1.2, 1.2, 1.2],
  },
  IconR3F: {
    path: "/models/IconR3F.glb",
    cuboidColliderArgs: [2.5, 0.25, 0.7],
    modelName: "IconR3F",
    scale: [0.85, 0.85, 0.85],
  },
  IconZustand: {
    path: "/models/IconZustand.glb",
    cuboidColliderArgs: [1, 0.25, 1],
    modelName: "IconZustand",
    scale: [1.5, 1.5, 1.5],
  },
  IconVite: {
    path: "/models/IconVite.glb",
    cuboidColliderArgs: [1.5, 0.25, 1.5],
    modelName: "IconVite",
    scale: [1.6, 1.6, 1.6],
  },
  IconThreeJS: {
    path: "/models/IconThreeJS.glb",
    cuboidColliderArgs: [1.3, 0.25, 1.3],
    modelName: "IconThreeJS",
    scale: [1.5, 1.5, 1.5],
  },
  IconGSAP: {
    path: "/models/IconGSAP.glb",
    cuboidColliderArgs: [0.9, 0.25, 1.9],
    modelName: "IconGSAP",
    scale: [1.75, 1.75, 1.75],
  },
  IconReactRouter: {
    path: "/models/IconReactRouter.glb",
    cuboidColliderArgs: [1.9, 0.25, 0.9],
    modelName: "IconReactRouter",
    scale: [1.6, 1.6, 1.6],
  },
  IconAxios: {
    path: "/models/IconAxios.glb",
    cuboidColliderArgs: [2.5, 0.25, 0.6],
    modelName: "IconAxios",
    scale: [0.85, 0.85, 0.85],
  },
  IconNetlify: {
    path: "/models/IconNetlify.glb",
    cuboidColliderArgs: [2.9, 0.25, 0.7],
    modelName: "IconNetlify",
    scale: [1.1, 1.1, 1.1],
  },
  IconHygraph: {
    path: "/models/IconHygraph.glb",
    cuboidColliderArgs: [3.2, 0.25, 0.8],
    modelName: "IconHygraph",
    scale: [1.5, 1.5, 1.5],
  },
  IconWebXr: {
    path: "/models/IconWebXR.glb",
    cuboidColliderArgs: [3.2, 0.25, 0.8],
    modelName: "IconWebXR",
    scale: [1.5, 1.5, 1.5],
  },
}
